title: Docs docs

versions:
  - '1'

sidebar_categories:
  null:
    - index
    - formatting
  Technical:
    - setup
    - recipes
    - config
    - redirects
github_repo: apollographql/docs-docs
content_root: source

url: https://www.apollographql.com/docs/docs/
root: /docs/docs/

public_dir: public/docs/docs

